---
- hosts: all
  user: root
  vars_files:
    - vars/defaults.yml

  roles:
    - webserver
    - database
    - sidekiq

  handlers: 
    - name: Restart puma
      action: service name=puma state=restarted
